In [286]:
#%matplotlib inline
import seWrapper as se
#import matplotlib.pyplot as plt
import numpy as np
reload(se)
import astropy.units as u

In [265]:
data = np.loadtxt('bg1_i_uncorrected.csv',delimiter=',')

In [266]:
data[0,:]

array([  2.01971243e+02,   2.04980473e+01,   2.54069000e+01,
         4.69500000e-01,   2.15000000e+00,   1.88000000e-01,
         0.00000000e+00])

In [267]:
catalog = se.seCatalog()

In [268]:
catalog.create_new_catalog_arrs(ra=data[:,0],dec=data[:,1],fil='i',mags=data[:,2],\
                                    merr=data[:,3],fwhm=data[:,4],ellipticity=data[:,5],flags=data[:,6])

In [269]:
fake_stars = se.fakeStarTests('field_1/NGVS_BG_1.I2.fits',\
                                catalog,config_file='i.sex',seeing=3.,zpt=30.0,\
                              pix_scale=0.187,write_true_phot=False,gain=39.5)

In [270]:
starlist_x,starlist_y,starlist_mags = fake_stars.makeStarList('foo',min_mag=18,max_mag=20,n_stars=1000)

In [271]:
starlist_mags

array([ 18.82351548,  19.60118953,  18.47857022,  18.2205954 ,
        19.40666   ,  19.31801295,  18.48830139,  19.38768609,
        18.25392384,  19.34102251,  19.03293928,  19.73593005,
        19.02438376,  19.46606947,  19.48549117,  18.11196309,
        19.68362219,  18.22510053,  18.47427801,  19.26072129,
        19.2188469 ,  19.21361588,  19.73304499,  19.72419923,
        19.81015667,  19.28468926,  18.77676558,  19.9850969 ,
        19.10578766,  19.35876669,  19.45385492,  18.68690741,
        19.79824411,  18.22457964,  18.90266843,  19.71996382,
        19.54266797,  18.24151823,  18.1604042 ,  19.73841661,
        19.60752888,  19.39985418,  18.04091182,  18.52124146,
        18.42820437,  18.33564432,  18.83641262,  18.92945087,
        18.62908237,  18.37440692,  18.92262773,  18.97993603,
        18.60387161,  18.70577967,  18.09762414,  18.53222449,
        18.31926097,  19.76756278,  19.56344702,  19.51231193,
        18.43381015,  19.93493234,  18.20215229,  19.52

In [344]:
fake_stars.genFakeCatalogs(n_stars=10000,min_mag=20,max_mag=27,n_iter=1,overwrite=True)

In [345]:
fake

NameError: name 'fake' is not defined

In [346]:
fake_stars.fake_cats['0'][0,:] - fake_stars.fake_cats['0'][1,:]

array([ -0.98613294,  -1.08552458,   0.63347297, ..., -74.52217881,
       -73.29504212, -73.78270875])

In [347]:
np.savetxt('bg1_i_fake_stars_2.csv',fake_stars.fake_cats['0'],delimiter=',',fmt='%10.10f')

In [348]:
data = np.loadtxt('bg1_i_fake_stars.csv',delimiter=',')

In [343]:
data.shape

(2, 10000)

In [329]:
phot_cat = fake_stars.phot
starlist_cat = fake_stars.starlist_cat
recovered_cat = fake_stars.recovered_cat
unrec_cat = fake_stars.unrec_cat

In [244]:
starlist_cat.mags['recovered'].shape

(146620,)

In [336]:
bright_rec = ((starlist_cat.mags['input'] < 22) & (starlist_cat.mags['recovered'] > 80))

In [337]:
np.sum(bright_rec)

66

In [149]:
from pyraf.iraf import artdata

In [152]:
mags= np.random.uniform(low=18,high=22,size=1000)

In [153]:
mags = np.random.uniform(low=22,high=26,size=1000)
x = np.random.uniform(high=fake_stars.header['naxis1'],size=1000)
y = np.random.uniform(high=fake_stars.header['naxis2'],size=1000)

In [338]:
def write_reg(ra,dec,size='2"',color='green',shape='circle',filename='regions.reg'):
    f = open(filename,'w')
    f.write('fk5\n')
    for i,j in zip(ra,dec):
        f.write(shape+' '+str(i)+' '+str(j)+' '+size+' # color='+color+'\n')
    f.close()     

In [339]:
ra = starlist_cat.coords[bright_rec].ra.degree
dec = starlist_cat.coords[bright_rec].dec.degree

In [340]:
write_reg(ra,dec,filename='unrec_bright.reg')

In [341]:
starlist_cat.mags['input']

array([ 99.999,  99.999,  99.999, ...,  99.999,  99.999,  99.999])