In [156]:
#%matplotlib inline
import seWrapper as se
#import matplotlib.pyplot as plt
import numpy as np
import fakeStars
reload(se)
reload(fakeStars)
import astropy.units as u

In [157]:
data = np.loadtxt('IUSNO_uncorrected.csv',delimiter=' ')

In [158]:
data[0,:]

array([ 151.289584 ,   -7.9652672,   99.       ,   99.       ,
          3.58     ,    0.774    ,   16.       ])

In [159]:
catalog = se.seCatalog()

In [160]:
catalog.create_new_catalog_arrs(ra=data[:,0],dec=data[:,1],fil='i',mags=data[:,2],\
                                    merr=data[:,3],fwhm=data[:,4],ellipticity=data[:,5],flags=data[:,6])

In [161]:
fake_stars = fakeStars.fakeStarTests('IUSNO.fits',\
                                catalog,config_file='IUSNO_completeness.seconfig',seeing=3.,zpt=27.70999908 ,\
                              pix_scale=0.2,write_true_phot=False,gain=1.,exptime=75.)

In [162]:
#starlist_x,starlist_y,starlist_mags = fake_stars.makeStarList('foo',min_mag=18,max_mag=20,n_stars=1000)

In [181]:
fake_stars.genFakeCatalogs(n_stars=5000,min_mag=13,max_mag=30,n_iter=1,overwrite=True,\
                           ymax=8000,ymin=500,xmax=10000,xmin=500,match_rad=2.*u.arcsec)

In [182]:
fake_stars.fake_cats['0'][0,:] - fake_stars.fake_cats['0'][1,:]

array([  3.50801967,   3.74296414,   3.5016582 , ..., -72.6779165 ,
       -71.03583482, -72.88477072])

In [196]:
np.savetxt('n3115_fake_stars_i.csv',fake_stars.fake_cats['0'],delimiter=',',fmt='%10.10f')

In [199]:
fake_stars.fake_cats['0'][1,:][500:600]

array([ 15.4912,  16.1131,  10.771 ,  99.999 ,  15.8844,  99.999 ,
        21.4364,  18.3851,  20.8299,   9.829 ,  13.6124,  19.0732,
        16.6994,  11.7244,  21.8499,  10.8981,   9.7328,  20.5693,
        15.3724,  14.1839,  21.4192,  11.2255,  17.8703,  11.4969,
        14.0641,  12.949 ,  99.999 ,  21.8756,  12.2075,   9.7325,
        20.0377,  99.999 ,  99.999 ,  22.094 ,  22.1567,  99.999 ,
        99.999 ,  20.7394,  15.3562,  18.9932,  22.0819,  21.2556,
        19.2043,  14.2248,  12.5152,  99.999 ,  20.4098,  19.7099,
         9.7082,  19.0185,  17.0583,  18.5473,  13.0228,  15.3263,
        20.2128,  17.5574,  20.3325,  10.7258,  21.9299,  21.9859,
        19.7067,  18.4857,  16.7024,  17.2022,  20.0299,  14.7139,
        17.5103,  16.8563,  11.7703,  20.0037,  21.1582,  99.999 ,
        22.1742,  99.999 ,  99.999 ,  11.5137,  15.3243,  12.7118,
        19.6734,  13.8581,  15.4217,  12.7196,  21.85  ,  17.6049,
        22.1577,  11.8765,  12.1051,  10.4876,  12.9409,  99.9

In [185]:
data = np.loadtxt('bg1_i_fake_stars.csv',delimiter=',')

IOError: [Errno 2] No such file or directory: 'bg1_i_fake_stars.csv'

In [186]:
data.shape

(85615, 7)

In [187]:
phot_cat = fake_stars.phot
starlist_cat = fake_stars.starlist_cat
recovered_cat = fake_stars.recovered_cat
unrec_cat = fake_stars.unrec_cat

In [188]:
starlist_cat.mags['recovered'].shape

(114024,)

In [189]:
bright_rec = ((starlist_cat.mags['input'] < 24) & (starlist_cat.mags['recovered'] > 80))

In [190]:
np.sum(bright_rec)

258

In [191]:
mags= np.random.uniform(low=18,high=22,size=1000)

In [192]:
mags = np.random.uniform(low=22,high=26,size=1000)
x = np.random.uniform(high=fake_stars.header['naxis1'],size=1000)
y = np.random.uniform(high=fake_stars.header['naxis2'],size=1000)

In [193]:
def write_reg(ra,dec,size='2"',color='green',shape='circle',filename='regions.reg'):
    f = open(filename,'w')
    f.write('fk5\n')
    for i,j in zip(ra,dec):
        f.write(shape+' '+str(i)+' '+str(j)+' '+size+' # color='+color+'\n')
    f.close()     

In [194]:
ra = starlist_cat.coords[bright_rec].ra.degree
dec = starlist_cat.coords[bright_rec].dec.degree

In [195]:
write_reg(ra,dec,filename='unrec_bright.reg')

In [341]:
starlist_cat.mags['input']

array([ 99.999,  99.999,  99.999, ...,  99.999,  99.999,  99.999])